name: 🚀 Deploy website on push to hosting
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install composer dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "8.3"
          dev: no
          args: --optimize-autoloader --no-dev
          php_extensions: gd zip

      - name: Install npm modules
        run: npm install

      - name: Run vite bundler
        run: npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.justnear.my.id
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/*
